### ISSUE TITLE
How can i build the module by myself?

### ISSUE THREAD

**Issue by UltraFeed** [Rudokhvist/ASF-Achievement-Manager#30]
I cloned the repo by
git clone --recursive https://github.com/Rudokhvist/ASF-Achievement-Manager

Then i am running build.bat, it creates /out/ASF-Achievement-Manager.zip

After that, I am placing the .dll file into ASF plugins folder and error occur, But if i am using the archive from GitHub releases, it works fine.

2024-04-18 18:15:54|ArchiSteamFarm-29332|INFO|ASF|InitPlugins() Инициализация Plugins...
2024-04-18 18:15:54|ArchiSteamFarm-29332|ERROR|ASF|InitPlugins() Не удалось из-за ошибки: ASF-Achievement-Manager, Version=0.3.1.0, Culture=neutral, PublicKeyToken=null
2024-04-18 18:15:54|ArchiSteamFarm-29332|ERROR|ASF|InitPlugins() System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
System.IO.FileNotFoundException: 
File name: 'ArchiSteamFarm, Version=6.0.2.4, Culture=neutral, PublicKeyToken=504f46588cc351a9'
System.IO.FileNotFoundException: 
File name: 'ArchiSteamFarm, Version=6.0.2.4, Culture=neutral, PublicKeyToken=504f46588cc351a9'
System.IO.FileNotFoundException: 
File name: 'ArchiSteamFarm, Version=6.0.2.4, Culture=neutral, PublicKeyToken=504f46588cc351a9'
System.IO.FileNotFoundException: 
File name: 'ArchiSteamFarm, Version=6.0.2.4, Culture=neutral, PublicKeyToken=504f46588cc351a9'
System.IO.FileNotFoundException: 
File name: 'ArchiSteamFarm, Version=6.0.2.4, Culture=neutral, PublicKeyToken=504f46588cc351a9'
System.IO.FileNotFoundException: 
File name: 'ArchiSteamFarm, Version=6.0.2.4, Culture=neutral, PublicKeyToken=504f46588cc351a9'
System.IO.FileNotFoundException: 
File name: 'ArchiSteamFarm, Version=6.0.2.4, Culture=neutral, PublicKeyToken=504f46588cc351a9'
System.IO.FileNotFoundException: 
File name: 'ArchiSteamFarm, Version=6.0.2.4, Culture=neutral, PublicKeyToken=504f46588cc351a9'

**Comment by Rudokhvist** [comment]
You need to specify ASF version that you want to target. So, basically run `build.bat <your_asf_version>`, like `build.bat 6.0.2.4` for example.
